## **データ整理**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import os
from tqdm import tqdm

from myUtils import reduce_mem_usage, get_agg_df

import gc

#### [参考]submissionファイルに合わせてaggurigationした学習データ作成
https://www.kaggle.com/sachina/convert-accuracy-to-uncertainty-poisson

In [3]:
sales_train_val = pd.read_csv(os.path.join("rawdata","sales_train_evaluation.csv")) # データの読み出し
agg_df = get_agg_df(sales_train_val)
agg_df

,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,...,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941,id
Total_X,32631,31749,23783,25412,19146,29211,28010,37932,32736,25572,...,54308,59921,42362,38777,37096,36963,42552,51518,54338,Total_X
CA_X,14195,13805,10108,11047,9925,11322,12251,16610,14696,11822,...,23037,24704,17721,16150,15678,16297,17430,23103,24644,CA_X
TX_X,9438,9630,6778,7381,5912,9006,6226,9440,9376,7319,...,12366,16249,12228,11370,10375,9162,12303,13681,14815,TX_X
WI_X,8998,8314,6897,6984,3309,8883,9533,11882,8664,6431,...,18905,18968,12413,11257,11043,11504,12819,14734,14879,WI_X
CA_1_X,4337,4155,2816,3051,2630,3276,3450,5437,4340,3157,...,6245,6707,4568,3949,3995,4136,4433,5764,6289,CA_1_X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HOUSEHOLD_2_516_TX_2,0,1,0,0,0,0,1,1,0,0,...,0,0,1,0,0,0,0,0,1,HOUSEHOLD_2_516_TX_2
HOUSEHOLD_2_516_TX_3,2,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,1,2,HOUSEHOLD_2_516_TX_3
HOUSEHOLD_2_516_WI_1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,HOUSEHOLD_2_516_WI_1
HOUSEHOLD_2_516_WI_2,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,HOUSEHOLD_2_516_WI_2
HOUSEHOLD_2_516_WI_3,0,1,0,1,0,1,1,1,0,0,...,1,0,0,0,0,0,0,0,0,HOUSEHOLD_2_516_WI_3

In [4]:
agg_df.to_pickle(os.path.join("mydata","agg_train_eval.pickle"))